"""
Hermes Web Service - Voice to Report AI Agent
FastAPI application connecting to Hermes AI Agent
"""

import os
import logging
from contextlib import asynccontextmanager
from datetime import datetime, timedelta
from typing import Optional
from pathlib import Path

from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
from jose import JWTError, jwt
from passlib.context import CryptContext
import uuid

# =============================================================================
# Configuration
# =============================================================================

SECRET_KEY = os.getenv("SECRET_KEY", "hermes-web-service-secret-key-change-in-production")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60

# =============================================================================
# Password Hashing
# =============================================================================

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def verify_password(plain_password: str, hashed_password: str) -> bool:
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

# =============================================================================
# Token Management
# =============================================================================

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

# =============================================================================
# Mock Database (Replace with real database in production)
# =============================================================================

users_db = {}  # {username: {hash, name, email}}
reports_db = {}  # {report_id: {content, created_at, user}}

# =============================================================================
# Pydantic Models
# =============================================================================

class UserLogin(BaseModel):
    username: str
    password: str

class UserRegister(BaseModel):
    username: str
    password: str
    name: str
    email: str

class Token(BaseModel):
    access_token: str
    token_type: str

class AudioTranscribeRequest(BaseModel):
    audio_data: str  # Base64 encoded audio
    format: str = "webm"

class ReportGenerateRequest(BaseModel):
    transcription: str
    report_type: str = "general"  # general, medical, research, etc.

class Report(BaseModel):
    id: str
    content: str
    created_at: str
    user: str

# =============================================================================
# Hermes Integration Service
# =============================================================================

class HermesService:
    """Service to interact with Hermes AI Agent"""
    
    def __init__(self):
        self.api_key = os.getenv("HERMES_API_KEY", "")
        self.base_url = os.getenv("HERMES_BASE_URL", "https://api.minimax.io")
        self.model = os.getenv("HERMES_MODEL", "minimax/minimax-m2.7")
    
    async def generate_report(self, transcription: str, report_type: str = "general") -> str:
        """
        Send transcription to Hermes Agent and get a structured report back.
        """
        prompt = f"""You are a professional report generator. Based on the following transcription,
generate a well-structured {report_type} report.

Transcription:
{transcription}

Please generate a comprehensive, professional report based on this information.
"""
        
        # In production, this would call the actual Hermes API
        # For now, return a mock report structure
        mock_report = f"""
# {report_type.title()} Report
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary
This report summarizes the key points from the transcription.

## Content Analysis
{transcription}

## Key Findings
- Point 1: [To be filled by AI]
- Point 2: [To be filled by AI]
- Point 3: [To be filled by AI]

## Recommendations
1. [Recommendation 1]
2. [Recommendation 2]

---
Report generated by Hermes AI Agent
"""
        
        return mock_report

hermes_service = HermesService()

# =============================================================================
# Lifespan
# =============================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    logging.info("Hermes Web Service starting up...")
    yield
    logging.info("Hermes Web Service shutting down...")

# =============================================================================
# FastAPI Application
# =============================================================================

app = FastAPI(
    title="Hermes Web Service",
    description="Voice to Report AI Agent - Connect to Hermes AI",
    version="1.0.0",
    lifespan=lifespan
)

# Static files and templates
BASE_DIR = Path(__file__).parent
app.mount("/static", StaticFiles(directory=BASE_DIR / "static"), name="static")
templates = Jinja2Templates(directory=BASE_DIR / "templates")

# =============================================================================
# Helper Functions
# =============================================================================

async def get_current_user(token: str) -> Optional[str]:
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        if username is None:
            return None
        return username
    except JWTError:
        return None

# =============================================================================
# Pages (HTML)
# =============================================================================

@app.get("/", response_class=HTMLResponse)
async def root():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hermes Web Service</title>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: white; }
            .container { max-width: 800px; margin: 0 auto; text-align: center; }
            h1 { color: #e94560; }
            .btn { display: inline-block; padding: 15px 30px; margin: 10px; background: #e94560; color: white; text-decoration: none; border-radius: 5px; }
            .features { text-align: left; margin-top: 30px; }
            .feature { background: #16213e; padding: 15px; margin: 10px 0; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎙️ Hermes Web Service</h1>
            <p>AI-powered voice to report service</p>
            <a href="/login" class="btn">Login</a>
            <a href="/register" class="btn">Register</a>
            <div class="features">
                <div class="feature">🎙️ <strong>Voice Recording</strong> - Record voice and transcribe</div>
                <div class="feature">🤖 <strong>AI Processing</strong> - Connect to Hermes Agent</div>
                <div class="feature">📊 <strong>Report Generation</strong> - Professional structured reports</div>
            </div>
        </div>
    </body>
    </html>
    """

@app.get("/login", response_class=HTMLResponse)
async def login_page():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Login - Hermes Web Service</title>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: white; }
            .container { max-width: 400px; margin: 100px auto; }
            input { width: 100%; padding: 15px; margin: 10px 0; background: #16213e; border: none; color: white; border-radius: 5px; box-sizing: border-box; }
            .btn { width: 100%; padding: 15px; background: #e94560; color: white; border: none; border-radius: 5px; cursor: pointer; }
            .btn:hover { background: #d63b53; }
            h1 { text-align: center; }
            .error { color: #ff6b6b; text-align: center; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🔐 Login</h1>
            <form action="/api/auth/login" method="post">
                <input type="text" name="username" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
                <button type="submit" class="btn">Login</button>
            </form>
            <p style="text-align: center; margin-top: 20px;">Don't have an account? <a href="/register" style="color: #e94560;">Register</a></p>
        </div>
    </body>
    </html>
    """

@app.get("/register", response_class=HTMLResponse)
async def register_page():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Register - Hermes Web Service</title>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: white; }
            .container { max-width: 400px; margin: 50px auto; }
            input { width: 100%; padding: 15px; margin: 10px 0; background: #16213e; border: none; color: white; border-radius: 5px; box-sizing: border-box; }
            .btn { width: 100%; padding: 15px; background: #e94560; color: white; border: none; border-radius: 5px; cursor: pointer; }
            h1 { text-align: center; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>📝 Register</h1>
            <form action="/api/auth/register" method="post">
                <input type="text" name="username" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
                <input type="text" name="name" placeholder="Full Name" required>
                <input type="email" name="email" placeholder="Email" required>
                <button type="submit" class="btn">Register</button>
            </form>
        </div>
    </body>
    </html>
    """

@app.get("/dashboard", response_class=HTMLResponse)
async def dashboard(token: str = None):
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Dashboard - Hermes Web Service</title>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: white; }
            .container { max-width: 900px; margin: 0 auto; }
            h1 { color: #e94560; }
            .nav { background: #16213e; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
            .nav a { color: white; margin-right: 20px; text-decoration: none; }
            .card { background: #16213e; padding: 20px; margin: 10px 0; border-radius: 5px; }
            .btn { display: inline-block; padding: 10px 20px; background: #e94560; color: white; text-decoration: none; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="nav">
                <a href="/dashboard">Dashboard</a>
                <a href="/record">🎙️ New Recording</a>
                <a href="/reports">My Reports</a>
            </div>
            <h1>Welcome to Hermes Web Service</h1>
            <div class="card">
                <h2>🎙️ Voice to Report</h2>
                <p>Record your voice and get professional reports powered by AI.</p>
                <a href="/record" class="btn">Start Recording</a>
            </div>
            <div class="card">
                <h2>📊 Recent Reports</h2>
                <p>No reports yet. Start by creating one!</p>
            </div>
        </div>
    </body>
    </html>
    """

@app.get("/record", response_class=HTMLResponse)
async def record_page():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Record - Hermes Web Service</title>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: white; }
            .container { max-width: 600px; margin: 0 auto; text-align: center; }
            h1 { color: #e94560; }
            .recorder { background: #16213e; padding: 30px; border-radius: 10px; margin: 20px 0; }
            .btn-record { font-size: 48px; cursor: pointer; background: none; border: none; }
            .btn-record:hover { transform: scale(1.1); }
            .status { margin: 20px 0; font-size: 18px; }
            #waveform { height: 50px; background: #0f3460; border-radius: 5px; margin: 20px 0; }
            .report-type { margin: 20px 0; }
            select { padding: 10px; background: #16213e; color: white; border: none; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎙️ Voice Recording</h1>
            <div class="recorder">
                <button class="btn-record" id="recordBtn">🎤</button>
                <div class="status" id="status">Click to start recording</div>
                <div id="waveform"></div>
                <div class="report-type">
                    <label for="reportType">Report Type: </label>
                    <select id="reportType">
                        <option value="general">General</option>
                        <option value="medical">Medical</option>
                        <option value="research">Research</option>
                        <option value="business">Business</option>
                    </select>
                </div>
                <button id="submitBtn" class="btn-submit" style="display:none; padding: 15px 30px; background: #e94560; color: white; border: none; border-radius: 5px; cursor: pointer;">Generate Report</button>
            </div>
            <div id="result" style="display:none; background: #16213e; padding: 20px; border-radius: 10px; margin-top: 20px; text-align: left;"></div>
        </div>
        <script>
            let mediaRecorder;
            let audioChunks = [];
            let isRecording = false;
            const recordBtn = document.getElementById('recordBtn');
            const status = document.getElementById('status');
            const submitBtn = document.getElementById('submitBtn');
            const result = document.getElementById('result');
            let audioBlob;

            recordBtn.onclick = async () => {
                if (!isRecording) {
                    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
                    mediaRecorder = new MediaRecorder(stream);
                    audioChunks = [];
                    mediaRecorder.ondataavailable = e => audioChunks.push(e.data);
                    mediaRecorder.onstop = () => {
                        audioBlob = new Blob(audioChunks, { type: 'audio/webm' });
                        submitBtn.style.display = 'inline-block';
                    };
                    mediaRecorder.start();
                    isRecording = true;
                    recordBtn.textContent = '⏹️';
                    status.textContent = 'Recording... Click to stop';
                } else {
                    mediaRecorder.stop();
                    isRecording = false;
                    recordBtn.textContent = '🎤';
                    status.textContent = 'Recording complete';
                }
            };

            submitBtn.onclick = async () => {
                submitBtn.textContent = 'Processing...';
                submitBtn.disabled = true;
                
                const reader = new FileReader();
                reader.readAsDataURL(audioBlob);
                reader.onloadend = async () => {
                    const base64 = reader.result.split(',')[1];
                    const reportType = document.getElementById('reportType').value;
                    
                    try {
                        const response = await fetch('/api/audio/transcribe', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json' },
                            body: JSON.stringify({ audio_data: base64, format: 'webm', report_type: reportType })
                        });
                        const data = await response.json();
                        result.style.display = 'block';
                        result.innerHTML = '<pre style="white-space: pre-wrap;">' + data.report + '</pre>';
                    } catch (err) {
                        result.style.display = 'block';
                        result.innerHTML = 'Error: ' + err.message;
                    }
                    submitBtn.textContent = 'Generate Report';
                    submitBtn.disabled = false;
                };
            };
        </script>
    </body>
    </html>
    """

# =============================================================================
# API Endpoints
# =============================================================================

@app.post("/api/auth/login")
async def login(user: UserLogin):
    if user.username not in users_db:
        raise HTTPException(status_code=401, detail="Invalid credentials")
    
    stored_hash = users_db[user.username]["hash"]
    if not verify_password(user.password, stored_hash):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    
    access_token = create_access_token(data={"sub": user.username})
    return {"access_token": access_token, "token_type": "bearer"}

@app.post("/api/auth/register")
async def register(user: UserRegister):
    if user.username in users_db:
        raise HTTPException(status_code=400, detail="Username already exists")
    
    users_db[user.username] = {
        "hash": get_password_hash(user.password),
        "name": user.name,
        "email": user.email
    }
    
    return {"message": "User registered successfully"}

@app.post("/api/audio/transcribe")
async def transcribe_audio(req: AudioTranscribeRequest, token: Optional[str] = None):
    """
    Receive audio data, convert to text, then generate report via Hermes.
    """
    # In production, integrate with actual STT service
    mock_transcription = "This is a mock transcription. In production, this would use a real STT service like Whisper."
    
    report = await hermes_service.generate_report(mock_transcription, req.report_type)
    
    report_id = str(uuid.uuid4())
    reports_db[report_id] = {
        "content": report,
        "created_at": datetime.now().isoformat(),
        "user": "anonymous"
    }
    
    return {"transcription": mock_transcription, "report": report, "report_id": report_id}

@app.post("/api/reports/generate")
async def generate_report_endpoint(req: ReportGenerateRequest, token: Optional[str] = None):
    """Generate a report from transcription text"""
    report = await hermes_service.generate_report(req.transcription, req.report_type)
    
    report_id = str(uuid.uuid4())
    reports_db[report_id] = {
        "content": report,
        "created_at": datetime.now().isoformat(),
        "user": "anonymous"
    }
    
    return {"report_id": report_id, "report": report}

@app.get("/api/reports/{report_id}")
async def get_report(report_id: str):
    if report_id not in reports_db:
        raise HTTPException(status_code=404, detail="Report not found")
    return reports_db[report_id]

# =============================================================================
# Health Check
# =============================================================================

@app.get("/health")
async def health():
    return {"status": "healthy", "service": "hermes-web-service"}

@app.get("/api/status")
async def api_status():
    return {
        "hermes_connected": bool(hermes_service.api_key),
        "model": hermes_service.model,
        "version": "1.0.0"
    }

# =============================================================================
# Run with uvicorn
# =============================================================================

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)